name: Feedback 💬
description: Suggestions or user input
title: "|"
type: "Feedback 💬"
projects: ["StaytunedLLP/67"]

body:
  - type: markdown
    attributes:
      value: |
        🚀 Speed Leads, Ship Every Day.  

  - type: textarea
    attributes:
      label: Issue Description
      value: |
        As a end user
        I want to report
        so that

        ### Why this is important
        
        1. 

        ### Files

        1. [File/Diagram Name](Link) - Brief description of the diagram

        ### Acceptance Criteria
        
        - [ ] 

        ### Additional Context