name: Flag 🏳️
description: Flag
title: "|"
type: "Flag 🏳️"
projects: ["StaytunedLLP/43"]

body:
  - type: textarea
    attributes:
      label: Issue Description
      description: Provide details about the feature flag being tracked.
      value: |
        # Feature Flag: <Your Flag Name Here>

        *This issue tracks the lifecycle, configuration, and removal plan for a specific feature flag.*

        ## Flag Description & Purpose

        <!--
        - What feature, behavior, or experiment does this flag control?
        - Why was this flag introduced? (e.g., gradual rollout, A/B testing, kill switch)
        - What is the intended user/business value of the feature behind the flag?
        -->

        <!-- Answer the questions above this line -->


        ## Flag Details

        - Repository: `${repoId}`
        - Metadata ID: `${metadataId}`
        - Flag ID: `${flagId}`
        - Parent Flags: (optional)

        **Command to fetch details:**
        ```bash
        stcli list --reponame <reponame> --metadataId <metadata-id> --flag <flag-key>
        ```
        *(Replace placeholders, including `<flag-key>` with the actual key/identifier for this flag)*

        ---

        ## Associated Issues and flags
        <!--
        - Link to any related issues files and numbers.
        - Link to any related feature flags.
        -->

  - type: markdown
    attributes:
      value: |
        :yellow_circle: **CAUTION**
        1. The future is AI. Embrace it, or be left behind. :robot:
        1. Search existing issues first to avoid duplicates. :dancing_women:

        :red_circle: **IMPORTANT**
        1. First flag it, then ship it with confidence! :white_flag:
        1. Your insights matter! Report issues to drive a change. :pushpin:

        Add [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) if needed.
