name: Person 👤
description: CRM contact for external individuals connected to StaytunedLLP
title: '|'
type: 'Person 👤'
projects: ['StaytunedLLP/59']

body:
  - type: markdown
    attributes:
      value: |
        🚀 Speed Leads, Ship Every Day.

  - type: textarea
    attributes:
      label: Person Details
      value: |
        **Full Name:**  
        **Role/Title:**  
        **Company/Organization:**  
        **Relationship Type:** (e.g., Client, Vendor, Partner, Prospect)  
        **Connection Owner (Internal):**  
        **Start Date of Relationship:**  
        **Location:**  

        ### Purpose of Connection
        - Briefly describe why this contact is connected to StaytunedLLP.

        ### Key Areas of Collaboration
        - List main projects, deals, or areas of engagement.

        ### Communication Preferences
        - Preferred channels, frequency, and contact details.

        <!-- For ongoing updates, use issue comments:
          - Recent Interactions
          - Next Steps / Follow-ups
          - Additional Notes
          - Agenda or Key Activities
          - Additional Context
        -->
        ### Agenda or Key Activities
        Outline the main agenda items or activities for this contact.  
        - 

        ### Additional Context
        Add any relevant background, links, or supporting information.
