name: Profile ℹ️ 
description: Social media or platform profile connected to an external organization or person
title: '|'
type: 'Profile ℹ️'
projects: ['StaytunedLLP/57']

body:
  - type: markdown
    attributes:
      value: |
        🚀 Speed Leads, Ship Every Day.

  - type: textarea
    attributes:
      label: Profile Overview
      value: |
        **Profile Name:**  
        **Platform (e.g., LinkedIn, Twitter, GitHub):**  
        **Associated Organization/Person:**  
        **Relationship Type:** (e.g., Client, Vendor, Partner, Prospect)  
        **Profile Owner (Internal Contact):**  
        **Profile Link:**  

        ### Purpose of Profile Connection
        Briefly describe why this profile is connected to StaytunedLLP or its projects.  
        - 

        ### Key Engagement Areas
        List main projects, campaigns, or areas of engagement involving this profile.  
        - 

        ### Communication Preferences
        Preferred channels, frequency, and contact details for profile-related interactions.  
        - 

        ### Success Metrics
        How will we measure the effectiveness of this profile connection?  
        - [Metric Name](Link) – Brief description

        ### Key Participants & Roles
        List the main participants (internal and external) and their responsibilities regarding this profile.  
        - 

        ### Recent Activities or Updates
        Outline recent posts, interactions, or activities relevant to this profile.  
        - 

        ### Additional Context
        Add any relevant background, links, or supporting information.
