name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "2.x"

      - name: Get module directory
        id: get_module_dir
        run: |
          # Assumes workflow file is in .github/workflows and module is in the repository root
          MODULE_DIR=$(basename $(pwd)/../..) # Navigate up two levels from .github/workflows
          echo "MODULE_DIRECTORY=$MODULE_DIR" >> $GITHUB_OUTPUT

      - name: Check for deno.json version change
        id: check_version_change
        run: |
          MODULE_DIR="${{ steps.get_module_dir.outputs.MODULE_DIRECTORY }}"
          cd "$MODULE_DIR"

          # Check if deno.json file was modified in the commit
          if ! git diff --name-only HEAD^ HEAD | grep -q 'deno.json'; then
            echo "deno.json file was not modified in module '$MODULE_DIR'. Skipping publish."
            echo "PUBLISH_REQUIRED=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "deno.json file modified in module '$MODULE_DIR'. Checking for version increase..."

          # Get the previous version from the previous commit
          OLD_VERSION=$(git show HEAD^:deno.json | jq -r .version)
          if [ -z "$OLD_VERSION" ]; then
            echo "Could not retrieve previous version for module '$MODULE_DIR'. Publishing anyway."
            echo "PUBLISH_REQUIRED=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get the current version
          CURRENT_VERSION=$(jq -r .version deno.json)

          # Compare versions using semantic versioning (requires a tool like `semver` or basic string comparison)
          # For simplicity, let's use basic string comparison and assume semantic versioning is followed
          if [[ "$CURRENT_VERSION" == "$OLD_VERSION" ]]; then
            echo "Version in deno.json has not increased for module '$MODULE_DIR'. Skipping publish."
            echo "PUBLISH_REQUIRED=false" >> $GITHUB_OUTPUT
          else
            echo "Version increased from $OLD_VERSION to $CURRENT_VERSION in module '$MODULE_DIR'. Proceeding with publish."
            echo "PUBLISH_REQUIRED=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish if version increased
        if: steps.check_version_change.outputs.PUBLISH_REQUIRED == 'true'
        run: |
          MODULE_DIR="${{ steps.get_module_dir.outputs.MODULE_DIRECTORY }}"
          cd "$MODULE_DIR"
          deno publish